config/routes.rb
Rails.application.routes.draw do
 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index';

  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create destroy]
    member do
      post 'mark_movie_watched/:movie_id', to: 'lists#mark_movie_watched', as: :mark_movie_watched
    end
  end
  get 'test', to: 'lists#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6, message: "Your comment must be at least 6 characters long." }
  validates :movie, uniqueness: { scope: :list, message: "this movie is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to lists_path
    else
      render 'lists/show'
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def test
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def mark_movie_watched
    movie = Movie.find(params[:movie_id])
    @list = @list = List.find(params[:id])
    movie.update(watched: true)
    redirect_to list_path(@list), notice: 'Movie marked as watched!'
  end

  private

  def list_params
    params.require(:list).permit(:name, :movie_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Cinzel+Decorative&family=Fredoka:wght@300;400&family=Mooli&family=Roboto&family=Tangerine&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%#= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="lists-container">
  <h1 class="list-title">
    Movie Watchlists
  </h1>

  <div class="lists">
    <% @lists.each do |list| %>
      <div class="movie-list <%= list.name.parameterize %>" style="background-image: url(<%= asset_path("#{list.name.parameterize}.jpg") %>);">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

  <div class="create-list">
    <h3>Create your new movie list</h3>
    <div class="list-form">
    <%= simple_form_for @list do |f| %>
      <%= f.input :name, label: false, placeholder: 'Name your new list' %>
      <div>
        <%= f.button :submit, "Create List" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/lists/show.html.erb
<h1 class="title-banner">
  <%= @list.name %>
</h1>



<div class="movie-grid">
  <% @movies.each do |movie| %>
    <div class="movie-card">
      <img src="<%= movie.poster_url %>" alt="<%= movie.title %> poster">
      <h3 class='movie-title'><%= movie.title %></h3>
      <p class='movie-overview'><%= movie.overview %></p>
      <p class='movie-rating text-info'>IMDB Rating: <%= movie.rating %></p>
      <% if movie.watched %>
        <div class="watched-watermark">Watched</div>
      <% end %>
      <% unless movie.watched %>
        <%= button_to "Mark as Watched", mark_movie_watched_list_path(@list, movie_id: movie.id), class: 'btn-watched' %>
      <% end %>
    </div>
  <% end %>
</div>


<div class="bookmark-movie">
  <%= simple_form_for [@list, Bookmark.new] do |f| %>
    <%= f.association :movie, label: false, prompt: "Find a movie" %>
    <%= f.input :comment, label: false, placeholder: "Add a comment" %>
    <%= f.button :submit, "Add Movie to List" %>
  <% end %>
</div>

<div class="back-btn">
  <%= link_to "Back to Watchlists", lists_path, class: "nav-link active" %>
</div>

app/views/lists/test.html.erb
<div class="my-flex">
  <h2>This is the title</h2>
  <p>This is some content</p>
  <%= image_tag(asset_path("pika.png"), class: 'pika') %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <div>
      <%= link_to root_path, class: 'text-decoration-none' do %>
      <%= image_tag 'watchlist-logo.png', style: "width: 40px; border-radius: 8px" %>
      <span class="navbar-brand mx-2">My Movie Watchlist</span>
      <% end %>
    </div>
    <div class="d-flex" id="navbarNavDropdown">
      <ul class="navbar-nav d-flex">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Movie Lists
          </a>
          <ul class="dropdown-menu list-dropdown">
            <% List.all.each do |list| %>
              <li class="">
                <%= link_to list.name, list_path(list), class: "dropdown-item" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>